# Generated by Django 4.2.9 on 2024-02-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("code", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=255)),
                ("trade_item_unit_descriptor", models.CharField(blank=True, max_length=255, null=True)),
                ("trade_item_unit_descriptor_name", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.PositiveIntegerField(default=0)),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("edeka_article_number", models.BooleanField(default=False)),
                ("gross_weight", models.FloatField()),
                ("net_weight", models.FloatField()),
                ("packaging", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[("Validated", "Validated"), ("Unvalidated", "Unvalidated")], max_length=255
                    ),
                ),
                ("unit_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("code", "type")},
            },
        ),
    ]
