# Generated by Django 4.2.9 on 2024-02-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_edeka_article_number",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="edeka_article_number",
            field=models.CharField(max_length=255),
        ),
    ]
